export const OrderStatus = Object.freeze({
    CREATED: "CREATED",
    APPROVED: "APPROVED",
    PREPARING: "PREPARING",
    READY_FOR_PICKUP: "READY_FOR_PICKUP",
    PICKED_UP: "PICKED_UP",
    DELIVERED: "DELIVERED",
    CANCELLED: "CANCELLED"
});